module.exports = [
    /*
    empty
    */
    {
        "name": "(ריק)",
        "description": "(ריק)",
        "age": null,
        "spouseGender": null,
        "spouseGenderAge": null,
        "marritalStatus": null,
        "workIncome": null,
        "otherIncome": null,
        "gender": null,
        "spouseTotalIncome": null,
        "spouseKnownRights": null,
        "totalIncome": null,
        "allowanceForDependents": null,
        "knownRights": null,
        "passingsAndChildrenUnder21AgeNumber": null,
        "passingsAndChildrenUnder18AgeNumber": null,
        "spouseEarnInabilityDegree": null,
        "civilStatus": null,
        "birthCountry": null,
        "spouseCivilStatus": null,
        "socialSecurityPayer": null,
        "earnInabilityDegree": null,
        "ownedProperty": false,
        "residenceType": null,
        "marriageYears": null,
        "disabledChildAllowancePercentage": null
    },
    {
        "name": "ראובן",
        "description": "דיור ציבורי: זכאי. קצבת אזרח ותיק: זכאי.",
        "age": 68,
        "spouseGender": "female",
        "spouseGenderAge": 63,
        "marritalStatus": "married",
        "workIncome": 1000,
        "otherIncome": 0,
        "gender": "male",
        "spouseTotalIncome": null,
        "spouseKnownRights": null,
        "totalIncome": null,
        "allowanceForDependents": "spouseAndChildren",
        "knownRights": [10, 11, 1947, 12],
        "passingsAndChildrenUnder21AgeNumber": null,
        "passingsAndChildrenUnder18AgeNumber": 3,
        "spouseEarnInabilityDegree": null,
        "civilStatus": "citizen",
        "birthCountry": "israel",
        "spouseCivilStatus": null,
        "socialSecurityPayer": null,
        "earnInabilityDegree": 77,
        "ownedProperty": false,
        "residenceType": "rent",
        "marriageYears": null,
        "disabledChildAllowancePercentage": null
    },
    {
        "name": "שמעון",
        "description": "דיור ציבורי: זכאי. קצבת אזרח ותיק: לא ידוע.",
        "age": 68,
        "spouseGender": "female",
        "spouseGenderAge": 61,
        "marritalStatus": "married",
        "workIncome": 1000,
        "otherIncome": 0,
        "gender": "male",
        "spouseTotalIncome": null,
        "spouseKnownRights": null,
        "totalIncome": null,
        "allowanceForDependents": "spouseAndChildren",
        "knownRights": [10, 11, 1947, 12],
        "passingsAndChildrenUnder21AgeNumber": null,
        "passingsAndChildrenUnder18AgeNumber": 3,
        "spouseEarnInabilityDegree": null,
        "civilStatus": "citizen",
        "birthCountry": "israel",
        "spouseCivilStatus": null,
        "socialSecurityPayer": null,
        "earnInabilityDegree": 77,
        "ownedProperty": false,
        "residenceType": "rent",
        "marriageYears": null,
        "disabledChildAllowancePercentage": null
    },
    {
        "name": "לוי",
        "description": "דיור ציבורי: לא זכאי. קצבת אזרח ותיק: זכאי.",
        "age": 68,
        "spouseGender": "female",
        "spouseGenderAge": 63,
        "marritalStatus": "married",
        "workIncome": 1000,
        "otherIncome": 0,
        "gender": "male",
        "spouseTotalIncome": null,
        "spouseKnownRights": null,
        "totalIncome": null,
        "allowanceForDependents": "spouseAndChildren",
        "knownRights": [10, 11, 1940, 12],
        "passingsAndChildrenUnder21AgeNumber": null,
        "passingsAndChildrenUnder18AgeNumber": 3,
        "spouseEarnInabilityDegree": null,
        "civilStatus": "citizen",
        "birthCountry": "israel",
        "spouseCivilStatus": null,
        "socialSecurityPayer": null,
        "earnInabilityDegree": 77,
        "ownedProperty": false,
        "residenceType": "rent",
        "marriageYears": null,
        "disabledChildAllowancePercentage": null
    },
    {
        "name": "יהודה",
        "description": "דיור ציבורי: לא זכאי. קצבת אזרח ותיק: לא ידוע.",
        "age": 68,
        "spouseGender": "female",
        "spouseGenderAge": 60,
        "marritalStatus": "married",
        "workIncome": 1000,
        "otherIncome": 0,
        "gender": "male",
        "spouseTotalIncome": null,
        "spouseKnownRights": null,
        "totalIncome": null,
        "allowanceForDependents": "spouseAndChildren",
        "knownRights": [10, 11, 1940, 12],
        "passingsAndChildrenUnder21AgeNumber": null,
        "passingsAndChildrenUnder18AgeNumber": 3,
        "spouseEarnInabilityDegree": null,
        "civilStatus": "citizen",
        "birthCountry": "israel",
        "spouseCivilStatus": null,
        "socialSecurityPayer": null,
        "earnInabilityDegree": 77,
        "ownedProperty": false,
        "residenceType": "rent",
        "marriageYears": null,
        "disabledChildAllowancePercentage": null
    }
];